### Домашнее задание 2

In [51]:
import numpy as np
import math

### Часть 1

##### 1. Установить, какие произведения матриц AB и BA определены, и найти размерности полученных матриц:

а) A — матрица 4×2, B — матрица 4×2;

б) A — матрица 2×5, B — матрица 5×3;

в) A — матрица 8×3, B — матрица 3×8;

г) A — квадратная матрица 4×4, B — квадратная матрица 4×4.

m - cтроки, n - столбцы

а) AB - не определена, т.к. 2 != 4
    BA - не определена, т.к. 2 != 4
    
б) AB - получится матрица 2х3
    BA - не определена, т.к. 3 != 2
    
в) AB - получится матрица 8х8
    BA - получится матрица 3х3
    
г) AB - матрица 4х4
    BA - матрица 4х4
    

##### 2. Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

A + B = ([[5, -3], [3, 5]])

In [2]:
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0,5]])

In [3]:
A + B

array([[ 5, -3],
       [ 3,  5]])

A * B = ([[4, -11], [12, -3]])

In [5]:
np.dot(A, B)

array([[  4, -11],
       [ 12,  -3]])

##### 3. Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

3A - 2B + 4C = ([[11, -5], [9, -12]])

In [7]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])

In [10]:
3*A - 2*B + 4*C

array([[ 11,  -5],
       [  9, -12]])

#### 4. Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

A_T = ([[4, 5, 2], [1, -2, 3]])

In [12]:
A = np.array([[4, 1], [5, -2], [2, 3]])

In [13]:
A.T

array([[ 4,  5,  2],
       [ 1, -2,  3]])

A * A_T = ([[16, 18, 11], [18, 29, 4], [11, 4, 13]])

In [14]:
np.dot(A, A.T)

array([[17, 18, 11],
       [18, 29,  4],
       [11,  4, 13]])

A_T * A = ([[45, 0], [0, 14]])

In [15]:
np.dot(A.T, A)

array([[45,  0],
       [ 0, 14]])

##### 5*. Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [46]:
def multi(m1, m2):
    if len(m1) == len(m2[0]): # проверка соответствию условия перемножения
        matrix = []
        m = len(m1)
        n = len(m2[0])
        i = 0
        while i != m:
            arr = []
            j = 0
            while j != n:
                p = 0
                x = 0
                while p != n:
                    x += m1[i][p] * m2[p][j]
                    p += 1
                arr.append(x)
                j += 1
            matrix.append(arr)
            i += 1
        return matrix
    else:
        print('Матрицы не соответствуют условиям перемножения')

In [49]:
A = np.array([[1, 7, 4], [3, -6, 2]])
B = np.array([[0, 5], [2, -1], [3, 4]])

In [50]:
multi(A, B)

[[14, -2], [-12, 21]]

### Часть 2

__1.__ Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    
   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$

In [60]:
# a)
A = np.array([[math.sin(x), -math.cos(x)], [math.cos(x), math.sin(x)]])
x = 1
det = math.sin(x) * math.sin(x) - math.cos(x) * (-math.cos(x))
det

1.0

In [58]:
np.linalg.det(A)

1.0

In [62]:
# б) Треугольная матрица
A = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])
det = 4 * 5 * 9
det

180

In [63]:
np.linalg.det(A)

180.0

In [69]:
# в)
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
det = 1*(5*9-6*8) - 2*(4*9-7*6) + 3*(4*8-7*5)
det

0

In [71]:
np.linalg.det(A)

-9.51619735392994e-16

### 2. Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.

а) det(A^2) = det(A)^2 = 16

б) по первому свойству определителей
det(A_T) = det(A) = 4

в) det(2A) = 2 * det(A) = 8

##### 3. Доказать, что матрица вырожденная.

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   


Матрица называется сингулярной, или вырожденной, если ее определитель равен нулю.


In [75]:
A = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])
np.linalg.det(A)

0.0

##### 4. Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

In [78]:
# a) 
A = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])

3я строка - сумма 1ой и 2ой строк. Можем ее отбросить
Следовательно ранг матрицы А = 2

In [77]:
np.linalg.matrix_rank(A)

2

In [79]:
# б)
B = np.array([[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 5, 6]])

3я строка - сумма 1ой и 2ой строк. Можем ее отбросить
Следовательно ранг матрицы B = 3

In [80]:
np.linalg.matrix_rank(B)

3